version: 2

builds: []

archives: []

changelog:
  use: github

  groups:
    - title: "Changelog"
      regexp: "(?i)(feat|feature|\\[feature\\]|\\[feat\\]|\\bFEATURE\\b|\\[BUGFIX\\]|\\bBUGFIX\\b|\\[bugfix\\])"
      order: 1
    - title: "Other changes"
      regexp: .*
      order: 99

  # filters:
  #   - '^docs:'    
  #   - '^chore:'

release:
  github:
    owner: Rishab87     
    name: kube-state-metrics      

  prerelease: "true"
  skip_upload: true

  header: |
    Changelog

  footer: |
    Full Changelog

    - Compare: {{ .GitURL }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    New Contributors

    {{- range .ReleaseNotesContributors }}
    - @{{ . }}
    {{- end }}

  mode: replace
