name: govulncheck

on:
  schedule:
    # Run every Monday
    - cron: '0 0 * * 1'

env:
  GO_VERSION: "^1.24"

permissions:
  contents: read

jobs:
  ci-security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        name: Checkout code
      - name: Set up Go 1.x
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install govulncheck binary
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run security checks
        run: |
          govulncheck ./...
