name: Post Release
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  promote-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          
      - name: Install kpromo
        run: go install sigs.k8s.io/promo-tools/v4/cmd/kpromo@latest
        
      - name: Extract release tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        
      # - name: Create image promotion PR
      #   run: |
      #     kpromo pr --fork=${{ github.actor }} -i \
      #       --project=kube-state-metrics \
      #       --tag=${{ steps.extract_tag.outputs.tag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge-back-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Extract release tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        
      - name: Create PR to merge release changes back to main
        run: |
          # Extract major.minor for branch name
          MAJOR_MINOR=$(echo "${{ steps.extract_tag.outputs.tag }}" | sed 's/v//' | cut -d. -f1,2)
          RELEASE_BRANCH="release-${MAJOR_MINOR}"
          
          gh pr create \
            --title "chore: Merge ${{ steps.extract_tag.outputs.tag }} back to main" \
            --body "Merge release changes from ${{ steps.extract_tag.outputs.tag }} back to main branch." \
            --base main \
            --head $RELEASE_BRANCH \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
